name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3' 

      - name: Build dictionary pages 🔧
        run: python3 deploy.py

      - name: Build search page 🔍
        run: python3 generate_search.py

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
