name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.13' 

      - name: Build dictionary pages 🔧
        run: python3 deploy.py

      - name: Build search page 🔍
        run: python3 generate_search.py

      - name: Set search page as index
        run: cp docs/search.html docs/index.html

      - name: Deploy to SF
        run: |
          wget -c https://dialectfonts.sourceforge.io/p1.woff2 -P docs
          wget -c https://dialectfonts.sourceforge.io/p2.woff2 -P docs
          sshpass -p '${{ secrets.SF_PASSWORD }}' scp -o StrictHostKeyChecking=no docs/index.html docs/*.woff2 ${{ secrets.SF_USERNAME }}@web.sourceforge.net:/home/project-web/taerv/htdocs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
